export default {
  hero: {
    buttonGroup: [
      {
        text: "Our Work",
        link: "#our-work",
        style: "default" as any,
      },
      {
        text: "Consult with an Expert",
        link: "/contact",
        style: "gradient" as any,
      },
    ],
    description:
      "Buchanan DevOps enables companies to design and develop their digital products and services while your team focuses on what they do best, running your business.",
    gradientBorder: true,
    subtitle: "Customers",
    title: "Meet Our",
    type: "landing" as any,
  },
  portfolio: [
    {
      id: "1",
      title: "Canopy Growth",
      url: "https://canopygrowth.com",
      href: "canopygrowth.com",
      image: "/portfolio/1.avif",
      alt: "Canopy Growth",
    },
    {
      id: "2",
      title: "Tweed",
      url: "https://tweed.com/en/all-cannabis-formats",
      href: "tweed.com",
      image: "/portfolio/2.avif",
      alt: "Tweed",
    },
    {
      id: "3",
      title: "BC Cannabis Stores",
      url: "https://bccannabisstores.com/collections/new-products",
      href: "bccannabisstores.com",
      image: "/portfolio/3.avif",
      alt: "BC Cannabis Stores",
    },
    {
      id: "4",
      title: "Deep Space",
      url: "https://deepspace.com/en",
      href: "deepspace.com",
      image: "/portfolio/4.avif",
      alt: "Deep Space",
    },
    {
      id: "5",
      title: "7 Acres",
      url: "https://7acres.com",
      href: "7acres.com",
      image: "/portfolio/5.avif",
      alt: "7 Acres",
    },
    {
      id: "6",
      title: "7 Acres - Craft",
      url: "https://7acres.com/craft",
      href: "7acres.com",
      image: "/portfolio/6.avif",
      alt: "7 Acres - Craft",
    },
    {
      id: "7",
      title: "Whisl",
      url: "https://enjoywhisl.com/en",
      href: "enjoywhisl.com",
      image: "/portfolio/7.avif",
      alt: "Whisl",
    },
    {
      id: "8",
      title: "Inflect",
      url: "https://inflect.com",
      href: "inflect.com",
      image: "/portfolio/8.avif",
      alt: "Inflect",
    },
    {
      id: "9",
      title: "Product Hunt",
      url: "https://producthunt.com",
      href: "producthunt.com",
      image: "/portfolio/9.avif",
      alt: "Product Hunt",
    },
    {
      id: "10",
      title: "The Pierre",
      url: "https://thepierreny.com",
      href: "thepierreny.com",
      image: "/portfolio/10.avif",
      alt: "The Pierre",
    },
    {
      id: "11",
      title: "Midrive",
      url: "https://midrive.com",
      href: "midrive.com",
      image: "/portfolio/11.avif",
      alt: "Midrive",
    },
    {
      id: "12",
      title: "Syneos Health",
      url: "https://syneoshealth.com",
      href: "syneoshealth.com",
      image: "/portfolio/12.avif",
      alt: "Syneos Health",
    },
    {
      id: "13",
      title: "Baldor Food",
      url: "https://baldorfood.com",
      href: "baldorfood.com",
      image: "/portfolio/13.avif",
      alt: "Baldor Food",
    },
    {
      id: "14",
      title: "Rail Works",
      url: "https://railworks.com",
      href: "railworks.com",
      image: "/portfolio/14.avif",
      alt: "Rail Works",
    },
    {
      id: "15",
      title: "Olistica Group",
      url: "https://olisticagroup.com",
      href: "olisticagroup.com",
      image: "/portfolio/15.avif",
      alt: "Olistica Group",
    },
    {
      id: "16",
      title: "Companion Agriculture",
      url: "https://companionag.com",
      href: "companionag.com",
      image: "/portfolio/16.avif",
      alt: "Companion Agriculture",
    },
    {
      id: "17",
      title: "Natura Biomaterials",
      url: "https://natureabiomaterials.com",
      href: "natureabiomaterials.com",
      image: "/portfolio/17.avif",
      alt: "Natura Biomaterials",
    },
    {
      id: "18",
      title: "Jordan Process",
      url: "https://jordanprocess.com",
      href: "jordanprocess.com",
      image: "/portfolio/18.avif",
      alt: "Jordan Process",
    },
    {
      id: "19",
      title: "Cascade Naturals",
      url: "https://cascade-naturals.com",
      href: "cascade-naturals.com",
      image: "/portfolio/19.avif",
      alt: "Cascade Naturals",
    },
    {
      id: "20",
      title: "Della Terra",
      url: "https://dellaterrapharma.com",
      href: "dellaterrapharma.com",
      image: "/portfolio/20.avif",
      alt: "Della Terra",
    },
    {
      id: "21",
      title: "Deer Creek Seed",
      url: "https://deercreekseed.com",
      href: "deercreekseed.com",
      image: "/portfolio/21.avif",
      alt: "Deer Creek Seed",
    },
    {
      id: "22",
      title: "Bowlmor Lanes",
      url: "https://bowlero.com",
      href: "bowlero.com",
      image: "/portfolio/22.avif",
      alt: "Bowlmor Lanes",
    },
    {
      id: "23",
      title: "CSA Group",
      url: "https://csagroup.org",
      href: "csagroup.org",
      image: "/portfolio/23.avif",
      alt: "CSA Group",
    },
    {
      id: "24",
      title: "IDV Solutions",
      url: "https://idv.net",
      href: "idv.net",
      image: "/portfolio/24.avif",
      alt: "IDV Solutions",
    },
  ],
}
